[package]
name = "crossterm-lifecycle"
version = "0.0.4"
edition = "2021"

[dependencies]
crossterm = "0.27"
env_logger = "0.11"
log = "0.4"
ratatui = "0.26"
tokio = { version = "1.44.0", features = ["full"] }
